# Generated by Django 4.1.3 on 2023-06-26 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delincuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.PositiveSmallIntegerField()),
                ('genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=1)),
                ('direccion', models.CharField(max_length=200)),
                ('ocupacion', models.CharField(max_length=255)),
                ('descripcion_fisica', models.TextField()),
                ('situacion_economica', models.TextField()),
                ('situacion_social', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Delito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.DateTimeField()),
                ('ubicacion', models.CharField(max_length=100)),
                ('da_materiales', models.TextField()),
                ('delincuente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototype_API.delincuente')),
            ],
        ),
        migrations.CreateModel(
            name='Oficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.PositiveSmallIntegerField()),
                ('genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=1)),
                ('direccion', models.CharField(max_length=200)),
                ('ocupacion', models.CharField(max_length=255)),
                ('descripcion_fisica', models.TextField()),
                ('rango', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pruebas',
            fields=[
                ('prueba', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sospechoso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.PositiveSmallIntegerField()),
                ('genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=1)),
                ('direccion', models.CharField(max_length=200)),
                ('ocupacion', models.CharField(max_length=255)),
                ('descripcion_fisica', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Testigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.PositiveSmallIntegerField()),
                ('genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=1)),
                ('direccion', models.CharField(max_length=200)),
                ('ocupacion', models.CharField(max_length=255)),
                ('descripcion_fisica', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoDelito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Victima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.PositiveSmallIntegerField()),
                ('genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=1)),
                ('direccion', models.CharField(max_length=200)),
                ('ocupacion', models.CharField(max_length=255)),
                ('descripcion_fisica', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PruebasDelito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('resultado', models.TextField()),
                ('fecha_prueba', models.DateTimeField()),
                ('lugar', models.CharField(max_length=100)),
                ('delito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototype_API.delito')),
                ('prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototype_API.pruebas')),
            ],
        ),
        migrations.AddField(
            model_name='pruebas',
            name='delito',
            field=models.ManyToManyField(through='prototype_API.PruebasDelito', to='prototype_API.delito'),
        ),
        migrations.AddField(
            model_name='delito',
            name='oficial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototype_API.oficial'),
        ),
        migrations.AddField(
            model_name='delito',
            name='sospechoso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototype_API.sospechoso'),
        ),
        migrations.AddField(
            model_name='delito',
            name='testigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototype_API.testigo'),
        ),
        migrations.AddField(
            model_name='delito',
            name='tipo_delito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototype_API.tipodelito'),
        ),
        migrations.AddField(
            model_name='delito',
            name='victima',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototype_API.victima'),
        ),
    ]
