# Generated by Django 4.1.3 on 2023-06-26 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encuestas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_terminada', models.DateTimeField()),
                ('tipo_encuesta', models.CharField(choices=[('Cualitativa', 'Cualitativa'), ('Cuantitativa', 'Cuantitativa')], max_length=12)),
                ('creado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recopilacion.encuestas')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Respuestas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recopilacion.encuestas')),
                ('pregunta', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recopilacion.preguntas')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analisis', models.URLField(unique=True)),
                ('creado', models.DateTimeField(auto_now=True)),
                ('actualizado', models.DateTimeField(auto_now_add=True)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recopilacion.encuestas')),
            ],
        ),
    ]
